import type { ColorTheme } from "../types/theme";

export const themes: ColorTheme[] = [
  // LIGHT THEMES
  {
    id: "bubble-gum",
    name: "Bubble Gum",
    colors: {
      primary: "#FB6F92",
      secondary: "#FF8FAB",
      tertiary: "#d34669",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#322c2e",
      textSecondary: "#d34669",
      buttonColor: "#FB6F92",
      buttonColorHover: "#d34669",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#FF8FABad",
      bgColor2: "#FFB3C6ad",
      primarySet: ["#d34669", "#FF8FAB"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#FB6F92", "#FF8FAB", "#d34669"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "vintage-scarlet",
    name: "Vintage Scarlet",
    colors: {
      primary: "#C1121F",
      secondary: "#FDF0D5",
      tertiary: "#669BBC",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#780000",
      textSecondary: "#669BBC",
      buttonColor: "#C1121F",
      buttonColorHover: "#780000",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#C1121Fad",
      bgColor2: "#669BBCad",
      primarySet: ["#C1121F", "#FDF0D5", "#669BBC"],
      textSet: ["#ffffff", "#780000", "#ffffff"],
      timeBadgeSet: ["#C1121F", "#FDF0D5", "#669BBC"],
      tagTextSet: ["#ffffff", "#780000", "#ffffff"],
    },
  },
  {
    id: "silly-witch",
    name: "Silly Witch",
    colors: {
      primary: "#ad2831",
      secondary: "#f6aa1c",
      tertiary: "#640D14",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#38040E",
      textSecondary: "#AD2831",
      buttonColor: "#AD2831",
      buttonColorHover: "#640D14",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#AD2831ad",
      bgColor2: "#f6aa1cad",
      primarySet: ["#AD2831", "#f6aa1c", "#640D14"],
      textSet: ["#ffffff", "#38040E", "#ffffff"],
      timeBadgeSet: ["#AD2831", "#f6aa1c", "#640D14"],
      tagTextSet: ["#ffffff", "#38040E", "#ffffff"],
    },
  },
  {
    id: "candy-pop",
    name: "Candy Pop",
    colors: {
      primary: "#fc621e",
      secondary: "#11dafe",
      tertiary: "#ff8f00",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#2c2d32",
      textSecondary: "#2cb7e3",
      buttonColor: "#fc621e",
      buttonColorHover: "#ff8f00",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#ff8f00ad",
      bgColor2: "#11dafead",
      primarySet: ["#fc621e", "#11dafe", "#ff8f00"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#fc621e", "#11dafe", "#ff8f00"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "fiery-phoenix",
    name: "Fiery Phoenix",
    colors: {
      primary: "#fa5c54",
      secondary: "#62cabc",
      tertiary: "#5c6ec0",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#3C4A8B",
      textSecondary: "#53B5A6",
      buttonColor: "#5c6ec0",
      buttonColorHover: "#3D4B8C",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#fa5c54ad",
      bgColor2: "#62cabcad",
      primarySet: ["#5c6ec0", "#fa5c54", "#62cabc", "#fa5c54"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#5c6ec0", "#fa5c54", "#62cabc"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "flying-bumblebee",
    name: "Flying Bumblebee",
    colors: {
      primary: "#ffb703",
      secondary: "#32343c",
      tertiary: "#fb8500",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#32343c",
      textSecondary: "#fb8500",
      buttonColor: "#32343c",
      buttonColorHover: "#1a1a28",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#ffb703ad",
      bgColor2: "#32343cad",
      primarySet: ["#ffb703", "#32343c"],
      textSet: ["#32343c", "#ffffff"],
      timeBadgeSet: ["#ffb703", "#32343c"],
      tagTextSet: ["#32343c", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "rice-princesses",
    name: "Rice Princesses",
    colors: {
      primary: "#ffc300",
      secondary: "#81c1f4",
      tertiary: "#f67c9d",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#2F3F69",
      textSecondary: "#F3688D",
      buttonColor: "#81c1f4",
      buttonColorHover: "#2F3F69",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#ffc300ad",
      bgColor2: "#81c1f4ad",
      primarySet: ["#ffc300", "#81c1f4", "#f67c9d"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#ffc300", "#81c1f4", "#f67c9d"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "dancing-kiwi",
    name: "Dancing Kiwi",
    colors: {
      primary: "#a7c957",
      secondary: "#99582a",
      tertiary: "#6a994e",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#386641",
      textSecondary: "#99582a",
      buttonColor: "#a7c957",
      buttonColorHover: "#6a994e",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#a7c957ad",
      bgColor2: "#99582aad",
      primarySet: ["#a7c957", "#f2e8cf", "#6a994e", "#99582a"],
      textSet: ["#ffffff", "#386641", "#ffffff", "#ffffff"],
      timeBadgeSet: ["#a7c957", "#f2e8cf", "#99582a"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "pastel-panda",
    name: "Pastel Panda",
    colors: {
      primary: "#8AC6BC",
      secondary: "#E294AC",
      tertiary: "#93B38E",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#524348",
      textSecondary: "#E294AC",
      buttonColor: "#E294AC",
      buttonColorHover: "#ba6d84",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#8AC6BCad",
      bgColor2: "#E294ACad",
      primarySet: ["#8AC6BC", "#E294AC", "#93B38E"],
      textSet: ["#f8f8f8"],
      timeBadgeSet: ["#8AC6BC", "#E294AC", "#93B38E"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "fresh-watermelon",
    name: "Fresh Watermelon",
    colors: {
      primary: "#00c6ac",
      secondary: "#e3375b",
      tertiary: "#26a1a1",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#26a1a1",
      textSecondary: "#e3375b",
      buttonColor: "#00c6ac",
      buttonColorHover: "#26a1a1",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#00c6acad",
      bgColor2: "#e3375bad",
      primarySet: ["#00c6ac", "#e3375b", "#26a1a1", "#e3375b"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#00c6ac", "#e3375b", "#26a1a1"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "deep-sea",
    name: "Deep Sea",
    colors: {
      primary: "#00cac3",
      secondary: "#27404f",
      tertiary: "#02adca",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#27404f",
      textSecondary: "#02adca",
      buttonColor: "#00cac3",
      buttonColorHover: "#02adca",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#27404fad",
      bgColor2: "#00cac3ad",
      primarySet: ["#00cac3", "#27404f", "#02adca", "#27404f"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#00cac3", "#27404f", "#02adca"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "antarctica-trip",
    name: "Antarctica Trip",
    colors: {
      primary: "#0077b6",
      secondary: "#90e0ef",
      tertiary: "#00b4d8",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#03045e",
      textSecondary: "#00b4d8",
      buttonColor: "#00b4d8",
      buttonColorHover: "#0077b6",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#0077b6ad",
      bgColor2: "#90e0efad",
      primarySet: ["#0077b6", "#90e0ef", "#00b4d8"],
      textSet: ["#ffffff", "#03045e", "#ffffff"],
      timeBadgeSet: ["#0077b6", "#90e0ef", "#00b4d8"],
      tagTextSet: ["#ffffff", "#03045e", "#ffffff"],
    },
  },
  {
    id: "coastal-breeze",
    name: "Coastal Breeze",
    colors: {
      primary: "#3b66e0",
      secondary: "#64e5b3",
      tertiary: "#5647a6",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#3b66e0",
      textSecondary: "#64e5b3",
      buttonColor: "#3b66e0",
      buttonColorHover: "#5647a6",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#3b66e0ad",
      bgColor2: "#64e5b3ad",
      primarySet: ["#3b66e0", "#64e5b3", "#5647a6"],
      textSet: ["#ffffff", "#5647a6", "#ffffff"],
      timeBadgeSet: ["#3b66e0", "#64e5b3", "#5647a6"],
      tagTextSet: ["#ffffff", "#5647a6", "#ffffff"],
    },
  },
  {
    id: "midnight-sky",
    name: "Midnight Sky",
    colors: {
      primary: "#003566",
      secondary: "#ffc300",
      tertiary: "#fb8500",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#001d3d",
      textSecondary: "#fb8500",
      buttonColor: "#003566",
      buttonColorHover: "#001d3d",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#003566ad",
      bgColor2: "#ffc300ad",
      primarySet: ["#003566", "#ffc300", "#001d3d", "#ffc300"],
      textSet: ["#ffffff", "#001d3d"],
      timeBadgeSet: ["#003566", "#ffc300", "#001d3d"],
      tagTextSet: ["#ffffff", "#001d3d", "#ffffff"],
    },
  },
  {
    id: "vibrant-alien",
    name: "Vibrant Alien",
    colors: {
      primary: "#7209b7",
      secondary: "#f72585",
      tertiary: "#4361ee",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#3a0ca3",
      textSecondary: "#f72585",
      buttonColor: "#7209b7",
      buttonColorHover: "#3a0ca3",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#4361eead",
      bgColor2: "#f72585ad",
      primarySet: ["#7209b7", "#f72585", "#4361ee"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#7209b7", "#f72585", "#4361ee"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "carnival-parade",
    name: "Carnival Parade",
    colors: {
      primary: "#f72585",
      secondary: "#fdc500",
      tertiary: "#7209b7",
      cardBackground: "#ffffffba",
      cardBorder: "#ffffff",
      textPrimary: "#560bad",
      textSecondary: "#f72585",
      buttonColor: "#7209b7",
      buttonColorHover: "#560bad",
      borderLight: "#e5e7eb",
      footerBackground: "#eff2f6",
      surfaceBackground: "#ffffff",
      surfaceText: "#1f2937",
      bgColor1: "#f72585ad",
      bgColor2: "#fdc500ad",
      primarySet: ["#f72585", "#fdc500", "#7209b7"],
      textSet: ["#ffffff", "#560bad", "#ffffff"],
      timeBadgeSet: ["#f72585", "#fdc500", "#7209b7"],
      tagTextSet: ["#ffffff", "#560bad", "#ffffff"],
    },
  },

  // DARK THEMES
  {
    id: "bubble-gum-dark",
    name: "Bubble Gum",
    isDark: true,
    colors: {
      primary: "#FB6F92",
      secondary: "#FF8FAB",
      tertiary: "#d34669",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#FF8FAB",
      buttonColor: "#FB6F92",
      buttonColorHover: "#d34669",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#FF8FABad",
      bgColor2: "#FFB3C6ad",
      primarySet: ["#d34669", "#FF8FAB"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#FB6F92", "#FF8FAB", "#d34669"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "vintage-scarlet-dark",
    name: "Vintage Scarlet",
    isDark: true,
    colors: {
      primary: "#C1121F",
      secondary: "#FDF0D5",
      tertiary: "#669BBC",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#7abce5",
      buttonColor: "#C1121F",
      buttonColorHover: "#780000",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#C1121Fad",
      bgColor2: "#669BBCad",
      primarySet: ["#C1121F", "#FDF0D5", "#669BBC"],
      textSet: ["#ffffff", "#780000", "#ffffff"],
      timeBadgeSet: ["#C1121F", "#FDF0D5", "#669BBC"],
      tagTextSet: ["#ffffff", "#780000", "#ffffff"],
    },
  },
  {
    id: "silly-witch-dark",
    name: "Silly Witch",
    isDark: true,
    colors: {
      primary: "#ad2831",
      secondary: "#f6aa1c",
      tertiary: "#640D14",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#f6aa1c",
      buttonColor: "#AD2831",
      buttonColorHover: "#640D14",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#AD2831ad",
      bgColor2: "#f6aa1cad",
      primarySet: ["#AD2831", "#f6aa1c", "#640D14"],
      textSet: ["#ffffff", "#38040E", "#ffffff"],
      timeBadgeSet: ["#AD2831", "#f6aa1c", "#640D14"],
      tagTextSet: ["#ffffff", "#38040E", "#ffffff"],
    },
  },
  {
    id: "candy-pop-dark",
    name: "Candy Pop",
    isDark: true,
    colors: {
      primary: "#fc621e",
      secondary: "#11dafe",
      tertiary: "#ff8f00",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#11dafe",
      buttonColor: "#fc621e",
      buttonColorHover: "#ff8f00",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#ff8f00ad",
      bgColor2: "#11dafead",
      primarySet: ["#fc621e", "#11dafe", "#ff8f00"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#fc621e", "#11dafe", "#ff8f00"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "fiery-phoenix-dark",
    name: "Fiery Phoenix",
    isDark: true,
    colors: {
      primary: "#fa5c54",
      secondary: "#62cabc",
      tertiary: "#5c6ec0",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#62cabc",
      buttonColor: "#5c6ec0",
      buttonColorHover: "#3D4B8C",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#fa5c54ad",
      bgColor2: "#62cabcad",
      primarySet: ["#5c6ec0", "#fa5c54", "#62cabc", "#fa5c54"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#5c6ec0", "#fa5c54", "#62cabc"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "flying-bumblebee-dark",
    name: "Flying Bumblebee",
    isDark: true,
    colors: {
      primary: "#ffb703",
      secondary: "#32343c",
      tertiary: "#fb8500",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#ffb703",
      buttonColor: "#ffb703",
      buttonColorHover: "#fb8500",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#ffb703ad",
      bgColor2: "#fb8500ad",
      primarySet: ["#ffb703", "#32343c"],
      textSet: ["#32343c", "#ffffff"],
      timeBadgeSet: ["#ffb703", "#32343c"],
      tagTextSet: ["#32343c", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "rice-princesses-dark",
    name: "Rice Princesses",
    isDark: true,
    colors: {
      primary: "#ffc300",
      secondary: "#92C7F2",
      tertiary: "#F7A1B8",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#F7A1B8",
      buttonColor: "#92C7F2",
      buttonColorHover: "#2F3F69",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#ffc300ad",
      bgColor2: "#92C7F2ad",
      primarySet: ["#ffc300", "#92C7F2", "#F7A1B8"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#ffc300", "#92C7F2", "#F7A1B8"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "dancing-kiwi-dark",
    name: "Dancing Kiwi",
    isDark: true,
    colors: {
      primary: "#a7c957",
      secondary: "#99582a",
      tertiary: "#6a994e",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#a7c957",
      buttonColor: "#a7c957",
      buttonColorHover: "#6a994e",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#a7c957ad",
      bgColor2: "#99582aad",
      primarySet: ["#a7c957", "#f2e8cf", "#6a994e", "#99582a"],
      textSet: ["#ffffff", "#386641", "#ffffff", "#ffffff"],
      timeBadgeSet: ["#a7c957", "#f2e8cf", "#99582a"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "pastel-panda-dark",
    name: "Pastel Panda",
    isDark: true,
    colors: {
      primary: "#8AC6BC",
      secondary: "#E294AC",
      tertiary: "#93B38E",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#E294AC",
      buttonColor: "#E294AC",
      buttonColorHover: "#ba6d84",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#8AC6BCad",
      bgColor2: "#E294ACad",
      primarySet: ["#8AC6BC", "#E294AC", "#93B38E"],
      textSet: ["#f8f8f8"],
      timeBadgeSet: ["#8AC6BC", "#E294AC", "#93B38E"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "fresh-watermelon-dark",
    name: "Fresh Watermelon",
    isDark: true,
    colors: {
      primary: "#00c6ac",
      secondary: "#e3375b",
      tertiary: "#26a1a1",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#00c6ac",
      buttonColor: "#00c6ac",
      buttonColorHover: "#26a1a1",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#00c6acad",
      bgColor2: "#e3375bad",
      primarySet: ["#00c6ac", "#e3375b", "#26a1a1", "#e3375b"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#00c6ac", "#e3375b", "#26a1a1"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "deep-sea-dark",
    name: "Deep Sea",
    isDark: true,
    colors: {
      primary: "#00cac3",
      secondary: "#29688d",
      tertiary: "#02adca",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#00cac3",
      buttonColor: "#00cac3",
      buttonColorHover: "#02adca",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#02adcaad",
      bgColor2: "#00cac3ad",
      primarySet: ["#00cac3", "#29688d", "#02adca", "#29688d"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#00cac3", "#29688d", "#02adca"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "antarctica-trip-dark",
    name: "Antarctica Trip",
    isDark: true,
    colors: {
      primary: "#0077b6",
      secondary: "#90e0ef",
      tertiary: "#00b4d8",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#90e0ef",
      buttonColor: "#00b4d8",
      buttonColorHover: "#0077b6",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#0077b6ad",
      bgColor2: "#90e0efad",
      primarySet: ["#0077b6", "#90e0ef", "#00b4d8"],
      textSet: ["#ffffff", "#03045e", "#ffffff"],
      timeBadgeSet: ["#0077b6", "#90e0ef", "#00b4d8"],
      tagTextSet: ["#ffffff", "#03045e", "#ffffff"],
    },
  },
  {
    id: "coastal-breeze-dark",
    name: "Coastal Breeze",
    isDark: true,
    colors: {
      primary: "#3b66e0",
      secondary: "#64e5b3",
      tertiary: "#5647a6",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#64e5b3",
      buttonColor: "#3b66e0",
      buttonColorHover: "#5647a6",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#3b66e0ad",
      bgColor2: "#64e5b3ad",
      primarySet: ["#3b66e0", "#64e5b3", "#5647a6"],
      textSet: ["#ffffff", "#5647a6", "#ffffff"],
      timeBadgeSet: ["#3b66e0", "#64e5b3", "#5647a6"],
      tagTextSet: ["#ffffff", "#5647a6", "#ffffff"],
    },
  },
  {
    id: "midnight-sky-dark",
    name: "Midnight Sky",
    isDark: true,
    colors: {
      primary: "#003566",
      secondary: "#ffc300",
      tertiary: "#fb8500",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#ffc300",
      buttonColor: "#003566",
      buttonColorHover: "#001d3d",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#fb8500ad",
      bgColor2: "#ffc300ad",
      primarySet: ["#003566", "#ffc300", "#001d3d", "#ffc300"],
      textSet: ["#ffffff", "#001d3d"],
      timeBadgeSet: ["#003566", "#ffc300", "#001d3d"],
      tagTextSet: ["#ffffff", "#001d3d", "#ffffff"],
    },
  },
  {
    id: "vibrant-alien-dark",
    name: "Vibrant Alien",
    isDark: true,
    colors: {
      primary: "#7209b7",
      secondary: "#f72585",
      tertiary: "#4361ee",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#f72585",
      buttonColor: "#7209b7",
      buttonColorHover: "#3a0ca3",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#4361eead",
      bgColor2: "#f72585ad",
      primarySet: ["#7209b7", "#f72585", "#4361ee"],
      textSet: ["#ffffff"],
      timeBadgeSet: ["#7209b7", "#f72585", "#4361ee"],
      tagTextSet: ["#ffffff", "#ffffff", "#ffffff"],
    },
  },
  {
    id: "carnival-parade-dark",
    name: "Carnival Parade",
    isDark: true,
    colors: {
      primary: "#f72585",
      secondary: "#fdc500",
      tertiary: "#7209b7",
      cardBackground: "#0f172aba",
      cardBorder: "#ffffff",
      textPrimary: "#ffffff",
      textSecondary: "#f72585",
      buttonColor: "#7209b7",
      buttonColorHover: "#560bad",
      borderLight: "#e5e7eb",
      footerBackground: "#0f172a",
      surfaceBackground: "#1e293b",
      surfaceText: "#f1f5f9",
      bgColor1: "#f72585ad",
      bgColor2: "#fdc500ad",
      primarySet: ["#f72585", "#fdc500", "#7209b7"],
      textSet: ["#ffffff", "#560bad", "#ffffff"],
      timeBadgeSet: ["#f72585", "#fdc500", "#7209b7"],
      tagTextSet: ["#ffffff", "#560bad", "#ffffff"],
    },
  },
];